/* tslint:disable */
/* eslint-disable */
/**
 * clickup client
 * You can follow along at [https://clickup20.docs.apiary.io/#introduction/oauth2](https://clickup20.docs.apiary.io/#introduction/oauth2).  You'll need your personal token for this, just change the authorization header to include it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * GoalsApi - axios parameter creator
 * @export
 */
export const GoalsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a Goal
         * @param {string} body 
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createaGoal: async (body: string, teamId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createaGoal.');
            }
            // verify required parameter 'teamId' is not null or undefined
            if (teamId === null || teamId === undefined) {
                throw new RequiredError('teamId','Required parameter teamId was null or undefined when calling createaGoal.');
            }
            const localVarPath = `/api/v2/team/{team_id}/goal`
                .replace(`{${"team_id"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please use previously created goal_id created before \"Get Goal\" for continuity
         * @summary Create a Key Result
         * @param {string} body Please use previously created goal_id created before &quot;Get Goal&quot; for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createaKeyResult: async (body: string, goalId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createaKeyResult.');
            }
            // verify required parameter 'goalId' is not null or undefined
            if (goalId === null || goalId === undefined) {
                throw new RequiredError('goalId','Required parameter goalId was null or undefined when calling createaKeyResult.');
            }
            const localVarPath = `/api/v2/goal/{goal_id}/key_result`
                .replace(`{${"goal_id"}}`, encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please paste goal_id from previously updated Goal for continuity
         * @summary Delete a Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteaGoal: async (goalId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'goalId' is not null or undefined
            if (goalId === null || goalId === undefined) {
                throw new RequiredError('goalId','Required parameter goalId was null or undefined when calling deleteaGoal.');
            }
            const localVarPath = `/api/v2/goal/{goal_id}`
                .replace(`{${"goal_id"}}`, encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please post key_result_id from the previously edited key_result for continuity. Please also delete the previously created Goal created for testing the \"Get Goal\" endpoint.
         * @summary Delete a Key Result
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteaKeyResult: async (keyResultId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'keyResultId' is not null or undefined
            if (keyResultId === null || keyResultId === undefined) {
                throw new RequiredError('keyResultId','Required parameter keyResultId was null or undefined when calling deleteaKeyResult.');
            }
            const localVarPath = `/api/v2/key_result/{key_result_id}`
                .replace(`{${"key_result_id"}}`, encodeURIComponent(String(keyResultId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please paste key_result_id from previously created key_result for continuity
         * @summary Edit a Key Result
         * @param {string} body Please paste key_result_id from previously created key_result for continuity
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editaKeyResult: async (body: string, keyResultId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling editaKeyResult.');
            }
            // verify required parameter 'keyResultId' is not null or undefined
            if (keyResultId === null || keyResultId === undefined) {
                throw new RequiredError('keyResultId','Required parameter keyResultId was null or undefined when calling editaKeyResult.');
            }
            const localVarPath = `/api/v2/key_result/{key_result_id}`
                .replace(`{${"key_result_id"}}`, encodeURIComponent(String(keyResultId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please paste goal_id after creating another Goal for continuity. 
         * @summary Get Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoal: async (goalId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'goalId' is not null or undefined
            if (goalId === null || goalId === undefined) {
                throw new RequiredError('goalId','Required parameter goalId was null or undefined when calling getGoal.');
            }
            const localVarPath = `/api/v2/goal/{goal_id}`
                .replace(`{${"goal_id"}}`, encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Goals
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoals: async (teamId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamId' is not null or undefined
            if (teamId === null || teamId === undefined) {
                throw new RequiredError('teamId','Required parameter teamId was null or undefined when calling getGoals.');
            }
            const localVarPath = `/api/v2/team/{team_id}/goal`
                .replace(`{${"team_id"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Please paste goal_id from previously created Goal for continuity
         * @summary Update a Goal
         * @param {string} body Please paste goal_id from previously created Goal for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateaGoal: async (body: string, goalId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateaGoal.');
            }
            // verify required parameter 'goalId' is not null or undefined
            if (goalId === null || goalId === undefined) {
                throw new RequiredError('goalId','Required parameter goalId was null or undefined when calling updateaGoal.');
            }
            const localVarPath = `/api/v2/goal/{goal_id}`
                .replace(`{${"goal_id"}}`, encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GoalsApi - functional programming interface
 * @export
 */
export const GoalsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a Goal
         * @param {string} body 
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createaGoal(body: string, teamId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).createaGoal(body, teamId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please use previously created goal_id created before \"Get Goal\" for continuity
         * @summary Create a Key Result
         * @param {string} body Please use previously created goal_id created before &quot;Get Goal&quot; for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createaKeyResult(body: string, goalId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).createaKeyResult(body, goalId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please paste goal_id from previously updated Goal for continuity
         * @summary Delete a Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteaGoal(goalId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).deleteaGoal(goalId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please post key_result_id from the previously edited key_result for continuity. Please also delete the previously created Goal created for testing the \"Get Goal\" endpoint.
         * @summary Delete a Key Result
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteaKeyResult(keyResultId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).deleteaKeyResult(keyResultId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please paste key_result_id from previously created key_result for continuity
         * @summary Edit a Key Result
         * @param {string} body Please paste key_result_id from previously created key_result for continuity
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editaKeyResult(body: string, keyResultId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).editaKeyResult(body, keyResultId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please paste goal_id after creating another Goal for continuity. 
         * @summary Get Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGoal(goalId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).getGoal(goalId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Goals
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGoals(teamId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).getGoals(teamId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Please paste goal_id from previously created Goal for continuity
         * @summary Update a Goal
         * @param {string} body Please paste goal_id from previously created Goal for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateaGoal(body: string, goalId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await GoalsApiAxiosParamCreator(configuration).updateaGoal(body, goalId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GoalsApi - factory interface
 * @export
 */
export const GoalsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a Goal
         * @param {string} body 
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createaGoal(body: string, teamId: number, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).createaGoal(body, teamId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please use previously created goal_id created before \"Get Goal\" for continuity
         * @summary Create a Key Result
         * @param {string} body Please use previously created goal_id created before &quot;Get Goal&quot; for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createaKeyResult(body: string, goalId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).createaKeyResult(body, goalId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please paste goal_id from previously updated Goal for continuity
         * @summary Delete a Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteaGoal(goalId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).deleteaGoal(goalId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please post key_result_id from the previously edited key_result for continuity. Please also delete the previously created Goal created for testing the \"Get Goal\" endpoint.
         * @summary Delete a Key Result
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteaKeyResult(keyResultId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).deleteaKeyResult(keyResultId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please paste key_result_id from previously created key_result for continuity
         * @summary Edit a Key Result
         * @param {string} body Please paste key_result_id from previously created key_result for continuity
         * @param {string} keyResultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editaKeyResult(body: string, keyResultId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).editaKeyResult(body, keyResultId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please paste goal_id after creating another Goal for continuity. 
         * @summary Get Goal
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoal(goalId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).getGoal(goalId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Goals
         * @param {number} teamId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoals(teamId: number, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).getGoals(teamId, options).then((request) => request(axios, basePath));
        },
        /**
         * Please paste goal_id from previously created Goal for continuity
         * @summary Update a Goal
         * @param {string} body Please paste goal_id from previously created Goal for continuity
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateaGoal(body: string, goalId: string, options?: any): AxiosPromise<void> {
            return GoalsApiFp(configuration).updateaGoal(body, goalId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GoalsApi - object-oriented interface
 * @export
 * @class GoalsApi
 * @extends {BaseAPI}
 */
export class GoalsApi extends BaseAPI {
    /**
     * 
     * @summary Create a Goal
     * @param {string} body 
     * @param {number} teamId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public createaGoal(body: string, teamId: number, options?: any) {
        return GoalsApiFp(this.configuration).createaGoal(body, teamId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please use previously created goal_id created before \"Get Goal\" for continuity
     * @summary Create a Key Result
     * @param {string} body Please use previously created goal_id created before &quot;Get Goal&quot; for continuity
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public createaKeyResult(body: string, goalId: string, options?: any) {
        return GoalsApiFp(this.configuration).createaKeyResult(body, goalId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please paste goal_id from previously updated Goal for continuity
     * @summary Delete a Goal
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public deleteaGoal(goalId: string, options?: any) {
        return GoalsApiFp(this.configuration).deleteaGoal(goalId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please post key_result_id from the previously edited key_result for continuity. Please also delete the previously created Goal created for testing the \"Get Goal\" endpoint.
     * @summary Delete a Key Result
     * @param {string} keyResultId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public deleteaKeyResult(keyResultId: string, options?: any) {
        return GoalsApiFp(this.configuration).deleteaKeyResult(keyResultId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please paste key_result_id from previously created key_result for continuity
     * @summary Edit a Key Result
     * @param {string} body Please paste key_result_id from previously created key_result for continuity
     * @param {string} keyResultId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public editaKeyResult(body: string, keyResultId: string, options?: any) {
        return GoalsApiFp(this.configuration).editaKeyResult(body, keyResultId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please paste goal_id after creating another Goal for continuity. 
     * @summary Get Goal
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public getGoal(goalId: string, options?: any) {
        return GoalsApiFp(this.configuration).getGoal(goalId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Goals
     * @param {number} teamId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public getGoals(teamId: number, options?: any) {
        return GoalsApiFp(this.configuration).getGoals(teamId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Please paste goal_id from previously created Goal for continuity
     * @summary Update a Goal
     * @param {string} body Please paste goal_id from previously created Goal for continuity
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApi
     */
    public updateaGoal(body: string, goalId: string, options?: any) {
        return GoalsApiFp(this.configuration).updateaGoal(body, goalId, options).then((request) => request(this.axios, this.basePath));
    }
}
